// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: snapshot_recovery_request.proto

package protobuf

import (
	_ "github.com/gogo/protobuf/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnapshotRecoveryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaderName *string                         `protobuf:"bytes,1,req,name=LeaderName" json:"LeaderName,omitempty"`
	LastIndex  *uint64                         `protobuf:"varint,2,req,name=LastIndex" json:"LastIndex,omitempty"`
	LastTerm   *uint64                         `protobuf:"varint,3,req,name=LastTerm" json:"LastTerm,omitempty"`
	Peers      []*SnapshotRecoveryRequest_Peer `protobuf:"bytes,4,rep,name=Peers" json:"Peers,omitempty"`
	State      []byte                          `protobuf:"bytes,5,req,name=State" json:"State,omitempty"`
}

func (x *SnapshotRecoveryRequest) Reset() {
	*x = SnapshotRecoveryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_recovery_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotRecoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRecoveryRequest) ProtoMessage() {}

func (x *SnapshotRecoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_recovery_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRecoveryRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRecoveryRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_recovery_request_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotRecoveryRequest) GetLeaderName() string {
	if x != nil && x.LeaderName != nil {
		return *x.LeaderName
	}
	return ""
}

func (x *SnapshotRecoveryRequest) GetLastIndex() uint64 {
	if x != nil && x.LastIndex != nil {
		return *x.LastIndex
	}
	return 0
}

func (x *SnapshotRecoveryRequest) GetLastTerm() uint64 {
	if x != nil && x.LastTerm != nil {
		return *x.LastTerm
	}
	return 0
}

func (x *SnapshotRecoveryRequest) GetPeers() []*SnapshotRecoveryRequest_Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *SnapshotRecoveryRequest) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

type SnapshotRecoveryRequest_Peer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	ConnectionString *string `protobuf:"bytes,2,req,name=ConnectionString" json:"ConnectionString,omitempty"`
}

func (x *SnapshotRecoveryRequest_Peer) Reset() {
	*x = SnapshotRecoveryRequest_Peer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_recovery_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotRecoveryRequest_Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRecoveryRequest_Peer) ProtoMessage() {}

func (x *SnapshotRecoveryRequest_Peer) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_recovery_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRecoveryRequest_Peer.ProtoReflect.Descriptor instead.
func (*SnapshotRecoveryRequest_Peer) Descriptor() ([]byte, []int) {
	return file_snapshot_recovery_request_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SnapshotRecoveryRequest_Peer) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SnapshotRecoveryRequest_Peer) GetConnectionString() string {
	if x != nil && x.ConnectionString != nil {
		return *x.ConnectionString
	}
	return ""
}

var File_snapshot_recovery_request_proto protoreflect.FileDescriptor

var file_snapshot_recovery_request_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x79, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x24, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x67,
	0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x8f, 0x02, 0x0a, 0x17, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x0a, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x4c, 0x61, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x02, 0x28, 0x04,
	0x52, 0x09, 0x4c, 0x61, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x4c,
	0x61, 0x73, 0x74, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x02, 0x28, 0x04, 0x52, 0x08, 0x4c,
	0x61, 0x73, 0x74, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x3c, 0x0a, 0x05, 0x50, 0x65, 0x65, 0x72, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x05,
	0x50, 0x65, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05,
	0x20, 0x02, 0x28, 0x0c, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x46, 0x0a, 0x04, 0x50,
	0x65, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x10, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x42, 0x39, 0xd8, 0xe1, 0x1e, 0x00, 0xe0, 0xe1, 0x1e, 0x01, 0xf0, 0xe1, 0x1e,
	0x01, 0xf8, 0xe1, 0x1e, 0x01, 0x80, 0xe2, 0x1e, 0x01, 0xa8, 0xe2, 0x1e, 0x01, 0xb8, 0xe2, 0x1e,
	0x01, 0xc0, 0xe2, 0x1e, 0x01, 0xc8, 0xe2, 0x1e, 0x01, 0xd0, 0xe2, 0x1e, 0x01, 0xe0, 0xe2, 0x1e,
	0x01, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
}

var (
	file_snapshot_recovery_request_proto_rawDescOnce sync.Once
	file_snapshot_recovery_request_proto_rawDescData = file_snapshot_recovery_request_proto_rawDesc
)

func file_snapshot_recovery_request_proto_rawDescGZIP() []byte {
	file_snapshot_recovery_request_proto_rawDescOnce.Do(func() {
		file_snapshot_recovery_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_snapshot_recovery_request_proto_rawDescData)
	})
	return file_snapshot_recovery_request_proto_rawDescData
}

var file_snapshot_recovery_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_snapshot_recovery_request_proto_goTypes = []interface{}{
	(*SnapshotRecoveryRequest)(nil),      // 0: protobuf.SnapshotRecoveryRequest
	(*SnapshotRecoveryRequest_Peer)(nil), // 1: protobuf.SnapshotRecoveryRequest.Peer
}
var file_snapshot_recovery_request_proto_depIdxs = []int32{
	1, // 0: protobuf.SnapshotRecoveryRequest.Peers:type_name -> protobuf.SnapshotRecoveryRequest.Peer
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_snapshot_recovery_request_proto_init() }
func file_snapshot_recovery_request_proto_init() {
	if File_snapshot_recovery_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_snapshot_recovery_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotRecoveryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_recovery_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotRecoveryRequest_Peer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_snapshot_recovery_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snapshot_recovery_request_proto_goTypes,
		DependencyIndexes: file_snapshot_recovery_request_proto_depIdxs,
		MessageInfos:      file_snapshot_recovery_request_proto_msgTypes,
	}.Build()
	File_snapshot_recovery_request_proto = out.File
	file_snapshot_recovery_request_proto_rawDesc = nil
	file_snapshot_recovery_request_proto_goTypes = nil
	file_snapshot_recovery_request_proto_depIdxs = nil
}
